// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLijYv90f0HWrfzTDEeLYUMsK_LudzGJ4',
    appId: '1:441255729831:web:7cba8521148f4da4991982',
    messagingSenderId: '441255729831',
    projectId: 'app-services-c8e3d',
    authDomain: 'app-services-c8e3d.firebaseapp.com',
    storageBucket: 'app-services-c8e3d.firebasestorage.app',
    measurementId: 'G-Q8C3D7BQNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUNBZI2LzRAFQqz5lmTfsdLLDC4Z0jfjg',
    appId: '1:441255729831:android:19de0e577fa46f43991982',
    messagingSenderId: '441255729831',
    projectId: 'app-services-c8e3d',
    storageBucket: 'app-services-c8e3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmf-FbA4qQSOdZbYg2wstKjCILiiSR_4w',
    appId: '1:441255729831:ios:9c02e284ed10e227991982',
    messagingSenderId: '441255729831',
    projectId: 'app-services-c8e3d',
    storageBucket: 'app-services-c8e3d.firebasestorage.app',
    iosBundleId: 'com.autoconect.push',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmf-FbA4qQSOdZbYg2wstKjCILiiSR_4w',
    appId: '1:441255729831:ios:b0ab99d1b2dbe7b7991982',
    messagingSenderId: '441255729831',
    projectId: 'app-services-c8e3d',
    storageBucket: 'app-services-c8e3d.firebasestorage.app',
    iosBundleId: 'com.example.firebasepractica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLijYv90f0HWrfzTDEeLYUMsK_LudzGJ4',
    appId: '1:441255729831:web:a5f32bf5113498a8991982',
    messagingSenderId: '441255729831',
    projectId: 'app-services-c8e3d',
    authDomain: 'app-services-c8e3d.firebaseapp.com',
    storageBucket: 'app-services-c8e3d.firebasestorage.app',
    measurementId: 'G-Z8SRLFXBXQ',
  );
}
